- src/core/common/field-is-valid.ts
- src/ionic/forms/field.html
- src/material/forms/field.html
> add ajf-validated if ajfFormula is validated,

- src/core/forms/form-renderer.ts
when instance field validation is undefined instance valid boolean should be true
> fix(form-renderer)

- src/core/chart/chart.ts
fix(chart.ts)  apply spread operator to to piecelabel options
> fix(core/chart): merge piecelabel options from json

- src/core/forms/forms.spec.ts
- src/material/forms/input-field.html
sum between number input field with some null generate concatenation
> fix(material/form): input field

- src/dev-app/mat-forms/BUILD.bazel
- src/dev-app/mat-forms/forms-demo.html
- src/dev-app/mat-forms/forms-demo.ts
- src/e2e-app/mat-form/mat-form-e2e.html
- src/e2e-app/mat-form/mat-form-e2e.module.ts
- src/e2e-app/mat-form/mat-form-e2e.ts
- src/ionic/forms/form.html
- src/material/forms/form.e2e.spec.ts
- src/material/forms/form.html
- src/material/forms/input-field.html
- src/material/forms/single-choice-field.html
- tools/public_api_guard/ionic/forms.d.ts
- tools/public_api_guard/material/forms.d.ts
add translate pipe to save button
add ng-content ajfFormTopToolbarButtons for adding buttons on top toolbar
> fix(form): template

- src/material/form-builder/form-builder-service.ts
now getCurrentForm returns an AjfForm without choiches and choicesOrigin attributes for every ajf fields with choiches
> fix(material/form-builder): output form should not repeat choice values for every choice field

- src/core/forms/BUILD.bazel
- src/core/forms/form-to-pdf/form-to-pdf.ts
- src/core/forms/form-to-pdf/vfs-fonts.d.ts
- src/core/forms/public-api.ts
- src/dev-app/mat-forms/forms-demo.html
- src/dev-app/mat-forms/forms-demo.ts
- tools/public_api_guard/core/forms.d.ts
Adds functionality for printing forms in pdf (to be compiled manually or with precompiled form data).
> feat(core/forms): form-to-pdf

- .github/CODEOWNERS
> Make robzan8 owner of form-to-pdf and report-to-pdf

- src/core/forms/form-to-pdf/form-to-pdf.ts
The interface didn't exactly match the one in @dewco/core/reports, creating problems.
> fix(core/forms): fix FormSchema interface in form-to-pdf

- src/core/forms/form.ts
- src/core/forms/interface/nodes-instances/repeating-node-instance.ts
- src/core/forms/interface/nodes/repeating-node.ts
- src/core/forms/utils/slides-instances/create-repeating-slide-instance.ts
- src/core/page-slider/page-slider.ts
- src/dev-app/ion-forms/form.ts
- src/dev-app/ion-forms/forms-demo.html
- src/dev-app/ion-forms/forms-demo.ts
- src/dev-app/mat-forms/form.ts
- src/ionic/forms/form.html
- src/ionic/forms/form.scss
- src/ionic/forms/form.ts
- src/material/forms/form.e2e.spec.ts
- src/material/forms/form.html
- src/material/forms/form.ts
- tools/public_api_guard/core/forms.d.ts
- tools/public_api_guard/ionic/forms.d.ts
- tools/public_api_guard/material/forms.d.ts
disableRemoval allow  you to disable all correctly compiled slides of the repeating slide.
> feat(page-slider): add disableRemoval mode in repeating slide

- src/core/common/string-identifier.ts
- src/material/form-builder/string-identifier-dialog.html
- src/material/form-builder/string-identifier-dialog.ts
- tools/public_api_guard/core/common.d.ts
show attribute in string identifier handling the type of visualization when the field is in repeating slide.
> feat(material/form-builder): add show attribute to string identifier

- .github/CODEOWNERS
of src/material, src/ionic, dev-app , e2e-app and CODEOWNERS
> build: make peppedeka owner

- CHANGELOG.md
Cherry-picks the changelog from the "12.1.x" branch to the next branch (master).
> docs: release notes for the v12.1.2 release

- src/core/reports/report-to-pdf/report-to-pdf.ts
Fixes https://taiga.gnucoop.com/project/trik-gnucoop-dev/us/1328
> fix(core/reports): report-to-pdf fixes (tg 1328)

- src/core/forms/random-ajf-context-generator.ts
- src/core/models/utils/expression-utils.ts
* fix(core/forms): now random ajf generators works with fields inside repetion slides.
* fix(core/models): now SUM works with repeating fields inside conditions.
* fix(core/models): now ALL_VALUES_OF works with repeating fields.
> fix(multiple): report from xls

- CHANGELOG.md
Cherry-picks the changelog from the "13.0.x" branch to the next branch (master).
> docs: release notes for the v13.0.0 release

- projects/core/reports/src/xls-report/hindikit-parser.ts
Introduces the function parseFunctionWithParams, which allows to parse a generic function.
As a result, a lot of repetitive code can be cleaned up.
> fix(core/reports): hindikit: generalized function parsing

- projects/core/models/src/expressions.spec.ts
- projects/core/models/src/utils/expression-utils.ts
fix(core/models): sort code identifiers to avoid generating invalid expressions when replacing variables names with corresponding values in formulas
> fix(core/models): sort code identifiers

- projects/core/models/src/utils/expression-utils.ts
- projects/core/reports/src/interface/widgets/paginated-list-widget.ts
- projects/core/reports/src/utils/widgets-instances/is-paginated-list-widget-instance.ts
- projects/core/reports/src/utils/widgets-instances/widget-to-widget-instance.ts
- projects/core/reports/src/utils/widgets/is-paginated-list-widget.ts
- projects/core/reports/src/utils/widgets/is-widget-with-content.ts
- projects/core/reports/src/xls-report/hindikit-parser.ts
- projects/core/reports/src/xls-report/xls-report.ts
- projects/core/table/src/table.ts
Add formula field for paginated widget.
Add a report function for list formdata in dynamic table.
> Fix widget

- projects/core/reports/src/xls-report/hindikit-parser.ts
Enables using JavaScript in xlsreport formulas.
> feat(core/reports): js in xlsreport formulas

- projects/core/table/src/table.scss
- projects/ionic/reports/src/column-widget.scss
- projects/material/reports/src/column-widget.scss
- projects/material/reports/src/paginated-table-widget.scss
> fix(core/reports): make reports responsive

- projects/core/models/src/utils/expression-utils.md
- projects/core/models/src/utils/expression-utils.spec.ts
- projects/core/models/src/utils/expression-utils.ts
- projects/core/reports/src/xls-report/hindikit-parser.ts
Fixes https://taiga.gnucoop.com/project/trik-gnucoop-dev/us/1918
> fix(core/reports): fix date functions

- projects/material/form-builder/src/form-builder-service.ts
- projects/material/form-builder/src/node-type-entry.html
- projects/material/node-icon/src/node-icon.html
- projects/material/node-icon/src/node-icon.ts
Also adds field types to the form builder.
> feat(material/forms): replace ajf-icons with material icons

- projects/material/form-builder/src/form-builder-module.ts
- projects/material/form-builder/src/form-builder-service.ts
- projects/material/form-builder/src/form-builder.html
- projects/material/form-builder/src/form-builder.scss
- projects/material/form-builder/src/form-builder.ts
- projects/material/form-builder/src/node-entry.html
- projects/material/form-builder/src/node-entry.scss
- projects/material/form-builder/src/node-entry.ts
- projects/material/form-builder/src/node-properties-name-validator.ts
- projects/material/form-builder/src/node-properties.html
- projects/material/form-builder/src/node-properties.scss
- projects/material/form-builder/src/node-properties.ts
Refactored Form Builder expand/collapse behavior, node properties form checks and component behavior.
Template and css fixes and improvements.
> refactor(material/form-builder): Form Builder improvements.

- projects/core/chart/src/chart.ts
- projects/core/reports/src/xls-report/xls-report.ts
Implemented chart options: stacked and beginAtZero
> feat(core/reports): xlsreport chart options

- projects/core/reports/src/xls-report/xls-report.ts
Also fixes https://taiga.gnucoop.io/project/trik-gnucoop-dev/us/4125
> fix(core/reports): fix xlsreport charts size and proportions

- projects/core/forms/src/form-renderer.ts
- projects/core/forms/src/utils/fields-instances/update-formula.ts
remove context modification to enable valuechanges on formula update
> fix(core/forms): enable cascade formula fields

- projects/core/models/src/utils/expression-utils.spec.ts
- projects/core/models/src/utils/expression-utils.ts
and GET_LABELS report functions
> fix(core/models): use choice origin name as prefix for APPLY_LABELS
